version: "3.4"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - 16686:16686
      - 14268
      - 14250
  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888   # pprof extension
      - 13133:13133 # health_check extension
      - 4317:4317   # OTLP gRPC receiver
      - 55670:55679 # zpages extension
    depends_on:
      - jaeger